import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const source = readFileSync("src/app/billing/page.tsx", "utf8");

describe("billing page status copy", () => {
  it("renders invoice and PayUNI order statuses as user-facing Chinese labels", () => {
    expect(source).toContain("invoiceStatusLabel");
    expect(source).toContain("paymentStatusLabel");
    expect(source).toContain("已退款");
    expect(source).toContain("待付款");
    expect(source).toContain("付款失敗");
    expect(source).toContain("退款，推薦折抵會依規則取消或沖回");
    expect(source).toContain("前往安全付款");
    expect(source).toContain("付款資料不由 InboxPilot 保存");
    expect(source).toContain("將前往 PayUNI 安全付款頁。");
    expect(source).toContain("客製方案需要由管理員手動開通；請先聯絡我們確認用量、折抵與付款安排。");
    expect(source).toContain("aria-describedby={checkoutReasonId}");
    expect(source).toContain("id={checkoutReasonId}");
    expect(source).toContain("focus-visible:ring-2 focus-visible:ring-[var(--primary)]");
    expect(source).toContain("mt-3 flex flex-col gap-2");
    expect(source).toContain("grid grid-cols-1 gap-2 sm:inline-grid sm:grid-cols-2");
    expect(source).toContain("mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4");
    expect(source).toContain("items-center justify-center rounded-md");
    expect(source).toContain("待確認折抵會取消");
    expect(source).toContain("完成上方方案付款後，這裡會顯示發票號碼、折抵金額與付款狀態。");
    expect(source).toContain("建立第一筆付款訂單後，這裡會顯示訂單編號、方案金額與付款狀態。");
    expect(source).toContain("最近建立的付款訂單與付款結果");
    expect(source).toContain("發票號碼");
    expect(source).toContain("Merchant Trade No");
    expect(source).toContain('text-[11px] font-semibold uppercase tracking-wide text-[var(--text-muted)] md:hidden');
    expect(source).toContain("md:grid md:grid-cols-5 md:gap-2");
    expect(source).toContain("md:grid md:grid-cols-4 md:gap-2");
    expect(source).toContain("已使用後才退款，會以沖回紀錄抵銷");
    expect(source).toContain("查看推薦活動");
    expect(source).toContain("查看折抵明細");
    expect(source).toContain("快速前往");
    expect(source).toContain("帳單與付款紀錄");
    expect(source).toContain("下面開始是實際建立過的發票與付款訂單");
    expect(source).toContain("transition hover:bg-[var(--ip-surface-muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--primary)] focus-visible:ring-offset-2");
    expect(source).toContain("inline-flex h-8 items-center justify-center rounded-md");
    expect(source).toContain("addonDisplayName");
    expect(source).toContain("對話保留 +180 天");
    expect(source).toContain("+5,000 訊息事件");
    expect(source).toContain("+1 個團隊席位");
    expect(source).toContain("PlanComparisonRows");
    expect(source).toContain("最多人升級");
    expect(source).toContain("安全付款說明");
    expect(source).toContain("方案升級選項");
    expect(source).toContain("先從目前方案與用量往下看");
    expect(source).toContain("付款會在 PayUNI 安全頁面完成，InboxPilot 不會保存卡號。");
    expect(source).toContain('const agencyPlan = billingPlans.find((plan) => plan.key === "agency") ?? null;');
    expect(source).toContain('const selfServePlans = billingPlans.filter((plan) => !["trial", "agency"].includes(plan.key));');
    expect(source).toContain("客製合作");
    expect(source).toContain("尚未開放線上購買");
    expect(source).toContain("尚未開放購買");
    expect(source).toContain("目前只支援方案訂閱付款");
    expect(source).toContain("付款成功後自動寫入 entitlement");
    expect(source).toContain("退款 / 作廢後的額度沖回");
    expect(source).toContain('data-current-plan={isCurrentPlan ? "true" : "false"}');
    expect(source).toContain("使用中");
    expect(source).toContain("這是目前使用中的方案，無需重複購買。");
    expect(source).toContain('disabled={isCurrentPlan || plan.customSales || !payuniStatus.checkoutEnabled}');
    expect(source).toContain('{isCurrentPlan ? "目前使用中" : checkoutButtonLabel(plan, payuniStatus)}');
    expect(source).not.toContain("Sandbox");
    expect(source).not.toContain("測試站");
    expect(source).not.toContain("Production gate");
    expect(source).not.toContain("production gate");
    expect(source).not.toContain("正式站受控開通");
    expect(source).not.toContain("{addon.name}");
    expect(source).not.toContain("<span>{invoice.status}</span>");
    expect(source).not.toContain("<span>{order.status}</span>");
  });
});
